### ISSUE TITLE
Block helpers are not working

### ISSUE THREAD

**Issue by lokeshs1010** [navjotdhanawat/dynamic-html-pdf#10]
I have used some block helpers in my handlebar files. When I convert it to Pdf, then those block helpers conditions are not worked.

For Ex; I have used {{#ifCond title '==' 'Dashboard' }} active {{/ifCond}}".
It worked in my original file but not in pdf

**Comment by navjotdhanawat** [comment]
@lokeshs1010 still you are having this issue or got solution?

**Comment by lokeshs1010** [comment]
@navjotdhanawat I didn't get the solution till now :(

**Comment by navjotdhanawat** [comment]
@lokeshs1010 I have added support for custom handlebar helpers. So you can now define your own helper for eg: 'ifCond' and use in template. I have also updated readme of this repo.

For example: Register helper inside js file:
```
// Custom If condition inside handlebar(JS file)
var pdf = require('dynamic-html-pdf');
pdf.registerHelper('ifCond', function (v1, v2, options) {
    if (v1 === v2) {
        return options.fn(this);
    }
    return options.inverse(this);
})
```
Utilize registered helper inside handlebar template:
```
{{#ifCond v1 v2}}
    {{v1}} is equals to {{v2}}
{{else}}
    Variables are not similar
{{/ifCond}}
```
