### ISSUE TITLE
Linux body font-size

### ISSUE THREAD

**Issue by angeloborrelli** [navjotdhanawat/dynamic-html-pdf#18]
Hello,
I'm trying to figure out why I got different results creating PDF on same software configuration but different OS. More details:
Config 1
Nodejs 13.13.0
dynamic-html-pdf@1.0.2
Windows 10 x64
===> GOT result1.pdf
[result1.pdf](https://github.com/navjotdhanawat/dynamic-html-pdf/files/5717425/result1.pdf)

Config 2
Nodejs 13.13.0
dynamic-html-pdf@1.0.2
Linux Ubuntu 18.04 LTS
===> GOT result2.pdf
[result2.pdf](https://github.com/navjotdhanawat/dynamic-html-pdf/files/5717426/result2.pdf)

Any help would be highly appreciated.
Best Regards
Angelo

**Comment by angeloborrelli** [comment]
For more details I send also html template i'm using to create document.
[order_template_it.html.txt](https://github.com/navjotdhanawat/dynamic-html-pdf/files/5717447/order_template_it.html.txt)

**Comment by navjotdhanawat** [comment]
@angeloborrelli I am not able to replicate it on my end. Instead of using font size in body you can manage using below html css.

html {
zoom: 0.55;
}

**Comment by angeloborrelli** [comment]
@navjotdhanawat 0.75 did the trick!

Thank you very much for your help.
