### ISSUE TITLE
Flexbox in HTML template not working

### ISSUE THREAD

**Issue by ElliotThiebaut** [navjotdhanawat/dynamic-html-pdf#21]
Hello,
I've just started to use this npm package and it looks really simple and powerful. However it seems that using flexbox in the template.html file is not working and the output PDf is not styled with those propreties.
Is this expected behaviour or is this a configuration probleme ?

Thanks !

**Comment by qcasey** [comment]
I found an [answer upstream](https://github.com/marcbachmann/node-html-pdf/issues/592#issuecomment-754618280) that worked for me.
