### ISSUE TITLE
Render a variable as html, not as plaintext

### ISSUE THREAD

**Issue by Larzsify** [navjotdhanawat/dynamic-html-pdf#3]
I have a variable that needs to be rendered in the template. The variable contains HTML. In the pdf the html is rendered as plain text. I need the html variable to be rendered as html. Is this possible with your template engine?

**Comment by navjotdhanawat** [comment]
@Larzsify I assume you are providing html as plain text in variable. So you can render html by using `{{{htmlContent}}}` as below.

For eg: 

```
var option = {
 username: "Larzsify",
 htmlBody: "<div>Hi, I just rendered HTML.</div>"
}
```

```
<div class="entry">
  <h1>Hello {{option.username}}</h1>
  <div class="body">
    {{{option.htmlBody}}}
  </div>
</div>
```
Ref: [HTML Escaping](http://handlebarsjs.com/#html-escaping)

**Comment by Larzsify** [comment]
Thank you very much!
